# Generated by Django 5.1.7 on 2025-04-23 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entradas', models.PositiveIntegerField()),
                ('asiento', models.CharField(max_length=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_funcion', to='funciones.funcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_usuario', to='usuarios.usuario')),
            ],
        ),
    ]
