# Generated by Django 5.1.7 on 2025-05-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='precio_total',
        ),
    ]
