# Generated by Django 5.1.7 on 2025-05-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0006_funcion_activa'),
        ('reservas', '0003_remove_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('funcion', 'asiento')},
        ),
    ]
