# Generated by Django 5.1.7 on 2025-05-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0007_alter_pelicula_titulo_asiento'),
        ('reservas', '0004_alter_reserva_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reserva',
            name='asientos',
            field=models.ManyToManyField(related_name='reservas_asiento', to='funciones.asiento'),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='asiento',
        ),
    ]
