# Generated by Django 5.1.7 on 2025-05-27 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0010_alter_sala_ubicacion'),
        ('reservas', '0005_alter_reserva_unique_together_reserva_asientos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funciones.asiento')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funciones.funcion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_reservados', to='reservas.reserva')),
            ],
            options={
                'unique_together': {('asiento', 'funcion')},
            },
        ),
    ]
