# Generated by Django 5.1.7 on 2025-05-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_asientoreservado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='asientos',
        ),
    ]
