# Generated by Django 5.1.7 on 2025-05-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0002_tipoformato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion',
            name='formato',
        ),
    ]
