# Generated by Django 5.1.7 on 2025-05-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0003_remove_funcion_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='tipo_formato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funciones', to='funciones.tipoformato'),
        ),
    ]
