# Generated by Django 5.1.7 on 2025-05-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0004_funcion_tipo_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='tipo_formato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='funciones', to='funciones.tipoformato'),
            preserve_default=False,
        ),
    ]
