# Generated by Django 5.1.7 on 2025-05-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0005_alter_funcion_tipo_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
