# Generated by Django 5.1.7 on 2025-05-21 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0006_funcion_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=5)),
                ('numero', models.PositiveIntegerField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='funciones.sala')),
            ],
            options={
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
