# Generated by Django 5.1.7 on 2025-05-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0007_alter_pelicula_titulo_asiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='nombre',
        ),
    ]
