# Generated by Django 5.1.7 on 2025-05-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0007_alter_pelicula_titulo_asiento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sala',
            name='asientos',
            field=models.ManyToManyField(related_name='salas_asiento', to='funciones.asiento'),
        ),
        migrations.RemoveField(
            model_name='asiento',
            name='sala',
        ),
    ]
