# Generated by Django 5.1.7 on 2025-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0009_alter_funcion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='ubicacion',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
