# Generated by Django 5.1.7 on 2025-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0011_alter_sala_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='ubicacion',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
