# Generated by Django 5.1.7 on 2025-05-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0011_alter_sala_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoformato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
