# Generated by Django 5.1.7 on 2025-05-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0012_alter_sala_ubicacion'),
        ('funciones', '0012_alter_tipoformato_precio'),
    ]

    operations = [
    ]
