# Generated by Django 5.1.7 on 2025-06-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0013_merge_20250529_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='capacidad',
        ),
    ]
