# Generated by Django 5.1.7 on 2025-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('duracion', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('posters', models.URLField()),
                ('clasificacion', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
                ('trailer', models.URLField()),
            ],
        ),
    ]
